# PyTorch_Tutorial_1 : What is PyTorch?

### 이 노트는 아래의 웹사이트의 코드를 따라가며 해설하였다.

https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [1]:
import torch

In [2]:
# Uninitialized matrix
x = torch.empty(5, 3)
print(x)

tensor([[-3.9191e-17,  7.7212e-43, -3.9191e-17],
        [ 7.7212e-43, -3.9189e-17,  7.7212e-43],
        [-3.9189e-17,  7.7212e-43, -3.9193e-17],
        [ 7.7212e-43, -3.9193e-17,  7.7212e-43],
        [-3.9209e-17,  7.7212e-43, -3.9209e-17]])


In [3]:
# Initialized matrix
# 0~1사이의 실수값을 무작위로 반환한다.
x = torch.rand(5, 3)
print(x)

tensor([[0.8271, 0.2165, 0.1064],
        [0.5031, 0.7067, 0.0906],
        [0.1734, 0.4993, 0.2109],
        [0.7419, 0.3670, 0.4605],
        [0.6500, 0.1201, 0.0914]])


In [4]:
# All-zero matrix with data type "long"
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

# All-one matrix with data type "double"
y = torch.ones(5, 2, dtype=torch.double)
print(y)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


In [5]:
# Matrix creation from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# Create a tensor based on an existing tensor.
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

# randn은 표준정규분포에서 무작위로 수를 추출한다.
x = torch.randn_like(x, dtype=torch.float)    # override dtype! (double -> float)
print(x)                                      # result has the same size as x: (5,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3523,  0.6065, -0.6724],
        [ 0.5848,  1.1447, -1.6026],
        [-0.5036,  0.7032,  0.5911],
        [ 0.3851, -0.3658, -0.3254],
        [-0.2845, -0.3634,  0.5753]])


In [7]:
print(x.size())    # torch.Size is Python tuple,so it supports all tuple operations.

torch.Size([5, 3])


In [8]:
# Addition op. 1
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.6375,  1.0453, -0.3404],
        [ 0.8753,  1.7695, -1.5949],
        [-0.1620,  0.7734,  1.2491],
        [ 0.7328, -0.0484,  0.2907],
        [-0.2493,  0.2015,  0.5869]])


In [9]:
# Addition op. 2
print(torch.add(x, y))

tensor([[ 0.6375,  1.0453, -0.3404],
        [ 0.8753,  1.7695, -1.5949],
        [-0.1620,  0.7734,  1.2491],
        [ 0.7328, -0.0484,  0.2907],
        [-0.2493,  0.2015,  0.5869]])


In [10]:
# Addition op. 3
result = torch.empty(5, 3)
torch.add(x, y, out=result)    # Insert added value into "result"
print(result)

tensor([[ 0.6375,  1.0453, -0.3404],
        [ 0.8753,  1.7695, -1.5949],
        [-0.1620,  0.7734,  1.2491],
        [ 0.7328, -0.0484,  0.2907],
        [-0.2493,  0.2015,  0.5869]])


In [11]:
# Any operation that mutates a tensor in-place is post-fixed with an _.
# For example: x.copy_(y), x.t_() will change x.
y.add_(x)   # y+=x in python standard grammar
print(y)

tensor([[ 0.6375,  1.0453, -0.3404],
        [ 0.8753,  1.7695, -1.5949],
        [-0.1620,  0.7734,  1.2491],
        [ 0.7328, -0.0484,  0.2907],
        [-0.2493,  0.2015,  0.5869]])


In [12]:
print(x[:, 1])    # All numbers in 2nd column

tensor([ 0.6065,  1.1447,  0.7032, -0.3658, -0.3634])


In [13]:
# Modify the "shape" of tensors.
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)    # the size -1 is inferred from other dimensions. (Here 2 is reasonable answer.)
print(x.size(), x)
print(y.size(), y)
print(z.size(), z)

torch.Size([4, 4]) tensor([[-0.1735, -0.1173,  0.3574, -0.1636],
        [-0.9378, -0.1166,  0.0676,  0.0577],
        [-0.1245,  0.7449, -1.0488, -0.2512],
        [ 0.7183,  0.1406,  0.2596, -1.8287]])
torch.Size([16]) tensor([-0.1735, -0.1173,  0.3574, -0.1636, -0.9378, -0.1166,  0.0676,  0.0577,
        -0.1245,  0.7449, -1.0488, -0.2512,  0.7183,  0.1406,  0.2596, -1.8287])
torch.Size([2, 8]) tensor([[-0.1735, -0.1173,  0.3574, -0.1636, -0.9378, -0.1166,  0.0676,  0.0577],
        [-0.1245,  0.7449, -1.0488, -0.2512,  0.7183,  0.1406,  0.2596, -1.8287]])


In [14]:
# From torch tensor to python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.1965])
1.1965175867080688


In [15]:
# Numpy bridge
a = torch.ones(5)
print(a)

b = a.numpy()    # From torch tensor to numpy array
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [16]:
# Both share the memory location(if torch tensor is on CPU and not a CharTensor).
# Changing one will change the other.
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [17]:
# From numpy array to torch tensor
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [18]:
# Let us run this cell only if CUDA is available
# We will use "torch.device" objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings "".to("cuda")""
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
print(torch.cuda.is_available())

tensor([2.1965], device='cuda:0')
tensor([2.1965], dtype=torch.float64)
True
